// Redmine
export const SET_REDMINE_ADDRESS = "SET_REDMINE_ADDRESS";
export const SET_REDMINE_KEY = "SET_REDMINE_KEY";

// Projects
export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
